### ISSUE TITLE
Rune portals work in creative mode only.

### ISSUE THREAD

**Issue by rewenx** [svenhjol/Strange#100]
You must provide all the required information below, or your issue will be ignored/closed.

**Describe the bug (required)**
Rune Portals work perfectly while in creative mode. When switching over to Survival, the portal stops working. When you try to walk in, it repels the character.

Tested several Rune Portals with different rune configurations, and I even tried using different rune colors. I checked config. I have "RunePortals enabled" = true.

**Versions (required)**
Strange 1.15.2 - 1.0.0 beta 5 hotfix1
Charm 1.15.2 -1.5.9
Forge 31.2.26

**Additional context (optional)**
Add any other context about the problem here that could help us track it down. For example, seed and coordinates, are you using optifine, have you changed the default config and what changes did you make?

**Comment by ridjack** [comment]
I don't think the Rune Portals ever ended up getting fully fleshed out. They were abandoned as a concept in 1.16, and the 1.15 versions are longer being updated. If they're not working now, I wouldn't expect to see that change.
