### ISSUE TITLE
(1.16.4) Odd Worldgen related to Waterlogging

### ISSUE THREAD

**Issue by DarianLStephens** [svenhjol/Strange#102]
From what I've seen, it appears Strange's structures will clear out pre-existing water from inside them. For example, a ruins on the edge of a river, or underground lakes for the foundations.
However, it also seems that waterlogging is an exception to this rule.
While regular water blocks are removed, any blocks which have become waterlogged during generation remain that way, and thus pour water everywhere.
Some examples:
In a foundation.
![2020-12-21_09 25 37](https://user-images.githubusercontent.com/15375876/102725916-831b4c80-436e-11eb-96ed-bbdb854cdcad.png)
In a surface ruin.
![2020-12-18_03 55 51](https://user-images.githubusercontent.com/15375876/102725924-9fb78480-436e-11eb-8519-30d4c76ec7e8.png)

**Comment by ridjack** [comment]
This is a vanilla bug that can sometimes be seen in villages, too. Nothing we can do about it, sadly.

**Comment by DarianLStephens** [comment]
Dang. Good to know, at least.
