### ISSUE TITLE
(1.16.4) Slight Name Change Suggestion

### ISSUE THREAD

**Issue by DarianLStephens** [svenhjol/Strange#103]
I suggest you change the advancement name 'Atarnative Transport' to 'Altar-native Transport', to make it clear that it's a pun.
So far, without fail, every time I've seen the advancement, I've thought 'That's an error, I should report that', and in fact only recently made the connection between the Runic Altar and the name of the advancement.

**Comment by ridjack** [comment]
Yes, clarity is good. Expect to see it in the next version. Thank you!
