### ISSUE TITLE
Multiplier for chance on mobs spawn barely increases the chance. Might not be intended

### ISSUE THREAD

**Issue by Insane96** [svenhjol/Strange#11]
https://github.com/svenhjol/Strange/blob/master/src/main/java/svenhjol/strange/outerlands/module/Outerlands.java#L56
Here, and even the next checks with `2 * multiplier`. Multiplier varies from 1.0 to ~1.63 which multiplied by 2 barely increase the chance for a mob to have a potion effect (since the check is 2 out of 8000 (which is either 0.025% at lowest multiplier or 0.0375% at max multiplier).
The same applies to xp bonus, can barely can be doubled.

I know this can be changed via scaleDifficulty but I don't think it's intended.

Also sorry not sorry for all the issues, I really like this mod and I want to see it grow in the best of ways.

**Comment by svenhjol** [comment]
I really appreciate the playtesting, so thanks for the reports. I will experiment with these figures and see if I can find something that fits better.
