### ISSUE TITLE
Totem of Enchanting behaving strangely.

### ISSUE THREAD

**Issue by ridjack** [svenhjol/Strange#13]
Using a11; when adding XP to a Totem the first time at ~14 levels, totem added something around 7000 XP. Breaking the Totem set me to level 56. Had my wife add 9 levels or so, took the totem to ~51000 exp and set me to level 123 on breaking. Using /experience afterwards had no effect on the totem; no matter what I store, it inevitably shows the same 51k number and sets me to level 123 on breaking.

**Comment by svenhjol** [comment]
Thanks for this. I'll look into it for the next alpha.

**Comment by svenhjol** [comment]
I'm struggling to repeat this. Attaching video link, please let me know if there's anything you want me to try on my local. https://peerwatch.xyz/videos/watch/8e292ff7-8606-4e61-9f5e-7322c3725d9a

**Comment by ridjack** [comment]
I'm on 1.15 now; I'll let you know if it still exists there.

**Comment by svenhjol** [comment]
Will test with levels

**Comment by svenhjol** [comment]
Tested with levels. Using both `xp add` and `xp set` to give the player levels results in the same: given levels don't get added to the totem. It seems only the points do. Tested in 1.14 and 1.15. If you can give me steps to repeat this I'll be happy to try it.

**Comment by ridjack** [comment]
I'm happy to call it a one-off issue or a conflict. I'll re-open if I encounter it again.
