### ISSUE TITLE
Having Strange installed disables swiftwolf rending gale flight from project E

### ISSUE THREAD

**Issue by TehFoxFire** [svenhjol/Strange#14]
Its in the title, I believe its because of the totem of flight. I don't have any relevant logs.

**Comment by svenhjol** [comment]
Huh. I could make it not render the particles if that mod is installed, maybe that would work?

**Comment by TehFoxFire** [comment]
I dont think its particles of any kind, as the ring works in creative but not in survival. Also, it only needs to be installed and not in the inventory. I don't know how you are doing the flight, but however it is being done is interfering with the rending gale.

**Comment by svenhjol** [comment]
I think this is related to #16

**Comment by svenhjol** [comment]
Closing since #16 was fixed, please reopen if still an issue.
