### ISSUE TITLE
Totem of Flight Clash with other Flying

### ISSUE THREAD

**Issue by Slither88** [svenhjol/Strange#16]
Playing with the latest version of strange and forge 28.2.0. When the totem of flight is enabled no other flight mechanics function at all only the totem allows flight. When the totem is disabled all flight functions properly.

**Comment by svenhjol** [comment]
Needs testing in beta 2

**Comment by svenhjol** [comment]
Please can you test this version?  https://github.com/svenhjol/Strange/releases/download/1.15.2-1.0.0-beta.2/Strange-1.15.2-1.0.0-beta.2-NOCOMPASS.jar

**Comment by Slither88** [comment]
Hi it seems that it is working fine now. Thank you

**Comment by svenhjol** [comment]
Great, thanks for the feedback.
