### ISSUE TITLE
Stone Circles always teleporting to new structures instead of the ones that are bound to them

### ISSUE THREAD

**Issue by Insane96** [svenhjol/Strange#17]
Teleport number one
![2020-04-06_09 22 10](https://user-images.githubusercontent.com/7185104/78533106-ad30dc80-77e8-11ea-8209-c9d2d96c1e71.png)
![2020-04-06_09 22 25](https://user-images.githubusercontent.com/7185104/78533108-ae620980-77e8-11ea-94d4-bc34a01a24ec.png)
Next teleport
![2020-04-06_09 27 46](https://user-images.githubusercontent.com/7185104/78533252-f6812c00-77e8-11ea-8510-3bd598dc511e.png)
![2020-04-06_09 27 51](https://user-images.githubusercontent.com/7185104/78533254-f719c280-77e8-11ea-858c-67b991309001.png)

**Comment by svenhjol** [comment]
Hmmmm.

**Comment by svenhjol** [comment]
OK, can confirm it's working as expected in 1.14. Testing in 1.15 now.

**Comment by svenhjol** [comment]
See discord :)
