### ISSUE TITLE
No Chunk Holder after ticket has been added

### ISSUE THREAD

**Issue by dreckz** [svenhjol/Strange#18]
Crash occurs while in vault.
[crash-2020-04-06_15.14.08-server.txt](https://github.com/svenhjol/Strange/files/4440605/crash-2020-04-06_15.14.08-server.txt)

**Comment by svenhjol** [comment]
Thanks, please download and test the version of Charm and Strange listed in the feedback here: https://github.com/svenhjol/Strange/issues/15
