### ISSUE TITLE
Server crashes after 2 minutes

### ISSUE THREAD

**Issue by 3dguru** [svenhjol/Strange#19]
crash report from server crash, after server loaded and I log in I am able to move around for about 2 minutes and crashes. I unloaded Strange mod and server operates fine 

https://pastebin.com/SrwmSZ0W

**Comment by 3dguru** [comment]
Server was able to run after disabling Runestones, but would like to use them

**Comment by svenhjol** [comment]
Thanks for the report. Please see this ticket and test the files listed there: https://github.com/svenhjol/Strange/issues/15
