### ISSUE TITLE
Totem Of Flying XP minimum too high

### ISSUE THREAD

**Issue by RyanCR03** [svenhjol/Strange#2]
Totem of flying stops working after somewhere around 201 levels

**Comment by RyanCR03** [comment]
you have to have more than 200 levels and some more xp points to start flying

**Comment by Insane96** [comment]
Seems to no longer happen in alpha10

**Comment by svenhjol** [comment]
I've made these values more sensible based on your feedback, and added a config option as the following:
```
	[Totems.TotemOfFlying]
		#Number of seconds of flying before some XP is consumed.
		"XP interval" = 1.0
		#Amount of XP consumed while flying.
		"XP amount" = 1
		#Durability of the totem. The totem takes a point of damage every time you take off.
		Durability = 32
```
