### ISSUE TITLE
Doing /locate command for Stone Circles and Vaults structures in modded dimensions that adds the structures will cause the world to hang forever. (1.15.2)

### ISSUE THREAD

**Issue by TelepathicGrunt** [svenhjol/Strange#22]
I have two mods that lets users be able to import other mod's structures into the two mod's own biomes in its own dimensions. The structure is properly added to the biome's structure and feature maps/lists and so, if the structure is setup properly, the structure should always spawn.

However, with Strange's Stone Circle and Vaults structures, the structures never spawns in the modded biomes and when doing /locate for them, the game gets stuck in an infinite loop of trying to find one but can't.

Looking at the code for Strange, I believe I see the issue. In both structure's hasStartAt methods, there is a validBiomes check in them. If any mod adds Strange's structure to their biomes, Minecraft will see the structure in the structure and feature list, think that dimension can spawn the structure, and then calls hasStartAt for every chunk possible without knowing that it will always return false.

https://github.com/svenhjol/Strange/blob/58e42fc029739ffaeda2d0439ff6e4f25cde89d0/src/main/java/svenhjol/strange/runestones/structure/StoneCircleStructure.java#L58
https://github.com/svenhjol/Strange/blob/ea02df4d37437ae9b325a5e333fb969fec08265e/src/main/java/svenhjol/strange/ruins/structure/VaultStructure.java#L51

The solution to this is very simple, the structures should be added by _biome.addStructure_ to the biomes you want them to spawn in and then remove the validBiome check out of hasStartAt since hasStartAt is for checking if a biome can spawn at a chunkpos but not for blacklisting biomes. By using _biome.addStructure_ to only the valid biomes you want, the structures will only spawn in those biomes but also allow other mods to import the structure to their biomes as well without causing a hang when doing /locate. And yeah, you can use the config during the _biome.addStructure_ phase.

Last thing, just be sure to do _biome.addFeature_ to all biomes so your structure does not get cut off when it spawns on the edge of a valid biome and goes into an invalid biome. Again, _biome.addStructure_ is used by Minecraft to determine what biome is valid for starting generation and _biome.addFeature_ is used to allow biomes to do the actual generation and not cut off structures. 

It's a weird and convoluted system that Mojang made but that's how it works.

I hope this helps! Let me know if you need any help or clarification. :)

**Comment by svenhjol** [comment]
Thanks for the detailed description. I'd be happy to accept a PR on this if you want to give it a shot. Otherwise, I'll try and find some time next week to look at this.

**Comment by TelepathicGrunt** [comment]
Yeah I can do a PR! It might take be a day or so depending on how much time I got but shouldn't take long

**Comment by svenhjol** [comment]
Sweet

**Comment by svenhjol** [comment]
Ok, I finally got the time to merge your PR. I've also backported the changes to 1.14 and ready to test. What are the mods that let you test the structures in other dimensions?

**Comment by TelepathicGrunt** [comment]
The main one I have been using is my mod called World Blender https://www.curseforge.com/minecraft/mc-mods/worldblender

If you add that to MC, it should automatically import the structures from all other mods and vanilla into its own dimension which should make /locate work. I did test the pr with world blender already by building a jar and testing /locate for Strange's structure in the dimension. But you should double check too to make sure it still works as intended. :)

**Comment by svenhjol** [comment]
Thanks, I'll test it now.

**Comment by svenhjol** [comment]
Works with Strange beta3 for 1.15.2, but 1.14.4 hangs forever. I guess I failed to backport your PR properly.

**Comment by TelepathicGrunt** [comment]
At least it works in 1.15.2! I'll fork the 1.14.4 branch later and see what's up. I might be able to find the issue for the backport.

**Comment by svenhjol** [comment]
I'd left a few lines in when I copied over your stuff. My bad, it works now in 1.14 :)
