### ISSUE TITLE
'Crash' on game start

### ISSUE THREAD

**Issue by BrisingrAerowing** [svenhjol/Strange#24]
[Various Logs](https://gist.github.com/BrisingrAerowing/25646a37114ab2c2e21624bf393a1a10)

The only change I've made since the last run is updating Culinary Construct. I'll test with the older version and see if that's the issue.

EDIT: The game starts correctly with the older version. The broken version is Culinary Construct beta3.

**Comment by svenhjol** [comment]
Thanks. I'll test it against that mod.

**Comment by BrisingrAerowing** [comment]
I’ve done some more testing, and it happened once more, then everything started working without any changes. The third start did download various files again, so maybe something was in an invalid state.

**Comment by svenhjol** [comment]
Ok, that's great. Thanks for testing. Closing this now but feel free to reopen if issue happens again.
