### ISSUE TITLE
I can't place obelisk block on top each other

### ISSUE THREAD

**Issue by FuryOfFools** [svenhjol/Strange#26]
Obelisk block on other obelisk block just disappears. Maybe I do not fully understand the principle of its work? 
Version: 1.15.2-1.0.0-beta.2

**Comment by Insane96** [comment]
Can confirm

**Comment by FuryOfFools** [comment]
> Can confirm, but shift-rightclicking works

This is still considered a bug, right?

**Comment by Insane96** [comment]
I think so, I don't think you can do something by rightclicking obelisks

Il Lun 13 Apr 2020, 20:13 FuryOfFools <notifications@github.com> ha scritto:
