### ISSUE TITLE
[1.14.4] Unclear from in-game UI on how to claim quest rewards

### ISSUE THREAD

**Issue by noobanidus** [svenhjol/Strange#28]
I completed a mine magma quest, clicked on the quest but was only given "Quit Quest" as an option. I clicked it, thinking perhaps this was how it was handed in, but apparently it just discarded all of my progress.

**Comment by svenhjol** [comment]
Ok. I'll make it clearer that you must find a scrollkeeper villager.

**Comment by svenhjol** [comment]
What do you think of renaming the button to "Abandon Quest"?

**Comment by svenhjol** [comment]
Here's how it looks so far:
![Screenshot from 2020-04-17 23-24-09](https://user-images.githubusercontent.com/26497903/79621353-9c466c00-8102-11ea-9904-06986862ee5b.png)

**Comment by noobanidus** [comment]
For people who have only ever gotten the scrolls through chests and who might not be aware of how the scrollkeeper villagers works, perhaps "Return to a Village scrollkeeper to hand in your completed quest!" might be a better alternative?

**Comment by svenhjol** [comment]
Yep, that's fair. I was in a rush to release tonight so the version in the screenshot has gone into beta3, but I'll make the text change for beta4.

**Comment by noobanidus** [comment]
And also clarification if it needs to be *a specific village Scrollkeeper* or not. I'm presuming that because of the fact that the quest was picked up from a chest that any suffices, but obviously with the one that (should) require you to be near a village, it needs to be a scrollkeeper *in that village*.

Is there currently (I haven't completed the quest or been able to accept the quest properly for the sheep) a way to see which "village" or at least the coordinates it was bound to for the sheep quest?

**Comment by svenhjol** [comment]
Good suggestions. I'll throw something together and post some screenshots later.

**Comment by svenhjol** [comment]
![Screenshot from 2020-04-18 23-59-12](https://user-images.githubusercontent.com/26497903/79674247-acc51800-81d0-11ea-9d31-8d0d04f9d72f.png)
With co-ordinates.  Co-ordinates disappear once the criteria is fulfilled.



![Screenshot from 2020-04-18 23-55-45](https://user-images.githubusercontent.com/26497903/79674255-b77fad00-81d0-11ea-8bc3-37a71dc396bd.png)
Message showing it can be handed in to any scrollkeeper.



![Screenshot from 2020-04-18 23-56-18](https://user-images.githubusercontent.com/26497903/79674262-cb2b1380-81d0-11ea-9335-4178e5794cc7.png)
Message showing it can be handed in to the scrollkeeper that issued it.

**Comment by svenhjol** [comment]
Also, the quest start was buggy. It should not have let you start the quest unless you were at a scrollkeeper. That has now been fixed for the next beta.

**Comment by noobanidus** [comment]
Ah, yes, "messaged showed but quest still started" was the main thing I noticed. Thanks! I'm looking forward to playing with this more.

**Comment by svenhjol** [comment]
There should be a build of beta4 soon. I'll notify here when it's ready for testing :)
