### ISSUE TITLE
[1.14.4] Novice quest of "return sheep to village" obtainable via dungeon loot

### ISSUE THREAD

**Issue by noobanidus** [svenhjol/Strange#29]
Pretty much what it says on the tin.

**Comment by svenhjol** [comment]
Does it say that you have to go to a scrollkeeper to begin the quest?

**Comment by noobanidus** [comment]
I'll triple check, I believe I was given the option to "begin quest" but I can't be certain. However, I still have it in my chests.

**Comment by noobanidus** [comment]
Okay, once beginning the quest, I've started it, but it gives a notice saying "You must be near a villager to start this quest".

**Comment by noobanidus** [comment]
And just gonna say, this one is a little unfair: ![](https://i.imgur.com/jkXORDX.png)

**Comment by svenhjol** [comment]
Hahaha! Ok, that's insane. I'll tweak that quest.

**Comment by svenhjol** [comment]
Here's the default definition for that question:
```json
{
  "lang": {
    "en": {
      "title": "Tridents",
      "description": "Gather tridents."
    }
  },
  "gather": {
    "minecraft:trident": 10
  },
  "rewards": {
    "items": {
      "minecraft:emerald": 3,
      "minecraft:trident[enchanted][common]": 1
    },
    "xp": {
      "count": 80
    }
  }
}
```
You must have a 4x multiplier on that quest, wow! Did you find it in a chest or was it an expensive villager trade?

**Comment by svenhjol** [comment]
Reduced from default of 10 to 3.

**Comment by noobanidus** [comment]
Oh, sorry, this was found in a chest! I've yet to actually encounter much in the way of villagers in that I haven't specifically interacted with any villagers yet.
