### ISSUE TITLE
Massive TPS Lag Upon Opening Cartographer House Chests

### ISSUE THREAD

**Issue by Windspren** [svenhjol/Strange#32]
The game becomes unresponsive when you open the chest inside a cartographer's house. Using tools from other mods, I've found that this applies to any chest marked with the cartographer village house loot table. I'm not sure if other loot tables are affected, but I'm pretty sure this is an issue with Strange's loot generation. 

The bug was first noticed in a modpack I'm building and was reproduced two additional times while running Strange alone.

Other loot tables are probably affected, but I haven't had the chance to test every loot table individually yet.

**Comment by svenhjol** [comment]
Just in time to get this into the next beta :)
