### ISSUE TITLE
Game hangs when trying to locate a Vault on a TerraForged world in version 1.15.2-1.0.0-beta.3.jar

### ISSUE THREAD

**Issue by JMZED** [svenhjol/Strange#33]
Whenever searching for a vault with /locate in a TerraForged world (and perhaps other world generators) the game freezes forever, additionally opening a pillager chest that presumably contains a vault map will also hang. However, it is possible to find stone circles and ruins, just not vaults.

**Comment by svenhjol** [comment]
In a terraforged world, are there extreme hills biomes?

**Comment by JMZED** [comment]
I used the Nature's Compass mod to search for a "Mountains" biome (Extreme hills were renamed in 1.13) and could not find them in a terraforged world. Is there a way to change which biomes Vaults can spawn in?

**Comment by svenhjol** [comment]
sorry, I meant Mountains :)
Yes, if it can't find the biome it will probably end up searching forever.
Humm, I didn't add the config for the biomes. I'm stupid. Check for beta4, I'll add it there.

**Comment by blufirephoto** [comment]
This issue has been addressed in beta 4. It's not yet released on CurseForge and was just released here about 5 days ago. But the update should fix the problem.

**Comment by Coranthes** [comment]
Tested and this has been resolved in beta 4.  Am currently playing on a server with TerraForged with no problems.
