### ISSUE TITLE
Ambient Sound Volume Setting Resets Upon Reloading

### ISSUE THREAD

**Issue by Windspren** [svenhjol/Strange#34]
The ambient sound setting in the config file is always reset to 1.0 after closing and reloading the game. I've tested this, and sometimes it seems to take 2-3 reloads before it resets, which is odd.

**Comment by svenhjol** [comment]
?!

**Comment by svenhjol** [comment]
Ambient sounds will be removed in the next beta. They're moved to a new mod https://github.com/svenhjol/Charmonium
