### ISSUE TITLE
Download Size

### ISSUE THREAD

**Issue by Leirday** [svenhjol/Strange#35]
The download size seems to be very unusual for a mod that isn't that big as other mods. (50.0MB) Is this normal or did I download the mod from the wrong source? (I downloaded the 1.15.2 version of it from CurseForge)

**Comment by svenhjol** [comment]
It's the ambience module. It has ogg files for every single biome, boosting its size. When it's out of beta, there will be an option to download without the ambient sounds.

**Comment by Leirday** [comment]
> It's the ambience module. It has ogg files for every single biome, boosting its size. When it's out of beta, there will be an option to download without the ambient sounds.

Ok! Thank you for replying so quickly.
