### ISSUE TITLE
[1.15.2] Repeatable crash with maps

### ISSUE THREAD

**Issue by Omen267901** [svenhjol/Strange#36]
Getting a 100% repeatable crash with the Stone Circle and Underground Ruin maps. Happens the instant I equip either of them (and uh, my world is currently bricked due to this.). The map doesn't even draw to the screen. It's worth noting I am able to hover over them in the inventory (which renders a preview) without that crashing.

Crashlog: [https://gist.github.com/Omen267901/63468302ccf396dcad121e555c0317b4](url)

**Comment by svenhjol** [comment]
Can you upgrade to Strange-beta3 and try your world again?

**Comment by Omen267901** [comment]
Will do ASAP.

**Comment by Omen267901** [comment]
Nope, still crashes on world launch. Here's the new log: https://gist.github.com/Omen267901/b846fe1d56a2e14ea77babc02c4503d6

**Comment by svenhjol** [comment]
So the log points to something internal that suggests the map colors are not setup correctly. Could you duplicate your world, remove all mods except Strange and Charm, and try booting the duplicated world? If it still crashes then, please zip that worldfile and attach here. Thanks.

**Comment by Omen267901** [comment]
The world launches properly with only Charm, Strange, and Biomes O' Plenty installed (which is only installed because it crashed when disabled)

**Comment by Omen267901** [comment]
I have a theory that it might be Phosphor, I'll check that specifically.

**Comment by svenhjol** [comment]
Ok, thanks for testing. Let me know what you discover!

**Comment by Omen267901** [comment]
I actually managed to find it _super_ quick luckily, it seems to be a game-breaking conflict with [Atmospheric](https://www.curseforge.com/minecraft/mc-mods/atmospheric), which is strange and very unfortunate. It's one of Quark's Friends mods, so I was hoping I wouldn't have any issues with it. Strange that vanilla treasure maps don't crash though.

**Comment by svenhjol** [comment]
Looks related to this open issue on their tracker: https://github.com/bageldotjpg/Atmospheric/issues/11
