### ISSUE TITLE
[1.15.2] Totem of Flying Not Always Activating

### ISSUE THREAD

**Issue by TrueDakkon** [svenhjol/Strange#37]
Totem of Flying seems to not work all the time. I have tried to use it at times even when at high levels and it won't activate its ability. Other times it won't move to the next level lower and will deactivate itself and then not start up again. There seems to be some Strange inconsistencies with when the totem wants to work or not.

**Comment by svenhjol** [comment]
Hi, thanks for the report. 
To debug the issue I need steps to reproduce it. If you can find out exactly when it occurs then I can start to fix it.

**Comment by svenhjol** [comment]
Closing, not enough information. Please reopen as necessary.
