### ISSUE TITLE
[1.15.2]Playerdata corrupted while holding a map

### ISSUE THREAD

**Issue by Giustitia** [svenhjol/Strange#39]
Hi there.
I've run into a bug and I think is Strange related. So, I was playing normally on my server until i grabbed a Ancient Ruins filled map, hold it in my hand, walked a little and suddenly I got kicked due to an error. Now I'm not able to login since as server start loading my playerdata it get an error. The other player kept playng normally. This is the crash, hope it help :/

https://pastebin.com/3XKqbdF6

I've performed some tests trying to get more information about what is actually crashing. Edited with NBTExplorer my player selectedItem value to prevent the crash on entering. Map works well until I reach some Z position (Y position on map) and I'm still out of it (more or less, if bottom-left corner of the map is 0 , 0 and without clamping values to 1 ,1, it crashes on 1.1 , 0.2 position). If I'm there and i select the map to be holded, server crash :D

**Comment by svenhjol** [comment]
Tracking the problem with Atmospheric here: https://github.com/svenhjol/Charm/issues/251
