### ISSUE TITLE
[1.15.2-beta3] Crash on world creation.

### ISSUE THREAD

**Issue by LeoBeliik** [svenhjol/Strange#49]
Log: https://hastebin.com/zadidopayi.pl
config: https://hastebin.com/unekopobus.bash
forge 31.1.63

Seems related to vaults gen, I've made changes in the config regarding vaults, so may be my fault.

**Comment by svenhjol** [comment]
Please can you repaste your config? I can't get the link to work for some reason.

**Comment by LeoBeliik** [comment]
Config: https://pastebin.com/EM0AzpW9
