### ISSUE TITLE
Chrash when taking a photo for the travel journal

### ISSUE THREAD

**Issue by marc-nicolas** [svenhjol/Strange#5]
My game crashes when the picture fot the travel journal is taken

**Comment by svenhjol** [comment]
Thanks for the report. Please can you let me know what other mods you are using, and also what operating system you play on - .e.g. Windows 10

**Comment by BaerliderFuchs** [comment]
Using Windows 10

**Modlist**
![image](https://user-images.githubusercontent.com/58077466/76831575-df719e80-6827-11ea-8615-5868a8f0f29b.png)

I found out, that it's the Blur-Mod (which blurs the background when a GUI is opened) that causes this issue, it works when I remove it.

Hope this helps!

**Comment by svenhjol** [comment]
Yes, that's a great help. thanks for getting back to me.

**Comment by svenhjol** [comment]
This should be fixed in alpha 11: https://github.com/svenhjol/Strange/releases/download/1.14.4-1.0.0-alpha.11/Strange-1.14.4-1.0.0-alpha.11.jar

**Comment by BaerliderFuchs** [comment]
Perfect! I'll let you know once i tried it out. Thank you!

**Comment by BaerliderFuchs** [comment]
It worked! Thank you for fixing this!
