### ISSUE TITLE
Java 11: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter

### ISSUE THREAD

**Issue by sargunv** [svenhjol/Strange#53]
Seems like my server host uses Java 11 by default, but the JAXB APIs are no longer in the classpath by default since Java 9. This is causing my server to crash on load. 

This just started happening the moment I cut a tree in a jungle, perhaps this specific code path was triggered upon picking up a certain item? I did have a quest active to pick up apples, which could have dropped in that moment.

[latest.log](https://github.com/svenhjol/Strange/files/4639803/latest.log)

**Comment by svenhjol** [comment]
Known issue since Forge team release 31.2.0, compatible with modern versions of Java. Should be fixed in beta 5.
