### ISSUE TITLE
Give some kind of invincibility when the player teleports with a runestone

### ISSUE THREAD

**Issue by Insane96** [svenhjol/Strange#6]
Most of the times you die by fall damage because the world takes time to load.

**Comment by Insane96** [comment]
I don't know if it's already done like this but what about starting generating the teleport location as soon as the pearl hits the RuneStone?

**Comment by svenhjol** [comment]
It would be the best approach, but I can't find any code in 1.14 that pregenerates the chunks in the destination location. I've created a bit of a hack to teleport the player there, back, then there again - as well as adding regeneration and slow fall.

Testing in survival and so far I've not run into any problems, but I'll release a test version with the changes soon.

**Comment by svenhjol** [comment]
Now done and configurable in beta1
