### ISSUE TITLE
Suggestion: Quest Scroll Addition

### ISSUE THREAD

**Issue by Tyrius1** [svenhjol/Strange#64]
Hi! just noticed the quest scrolls and I really like them.
Do you think it would be possible to add more configuration to these? 
Perhaps a separate config for pack devs to create their own quests?
And a stretch,
Possibly Project MMO integration?
Where the quests could require the player to reach a certain level in a certain skill.
Thanks you for your time!

**Comment by svenhjol** [comment]
There will be the ability to create new quests in an upcoming version :)

**Comment by svenhjol** [comment]
Todo: write instructions on how to create datapacks with custom quests.
