### ISSUE TITLE
Quark's Cave Roots spawn floating (attached to no block) inside Vaults

### ISSUE THREAD

**Issue by Insane96** [svenhjol/Strange#7]
![2020-03-19_10 44 08](https://user-images.githubusercontent.com/7185104/77053406-97d94700-69ce-11ea-896a-c4ef47cbd574.png)
![2020-03-19_10 44 01](https://user-images.githubusercontent.com/7185104/77053408-9871dd80-69ce-11ea-839d-f79ceb9fb8f6.png)

**Comment by svenhjol** [comment]
I know. It's super frustrating, and it also happens in Quark's Big Dungeons. I tried to solve it but there doesn't seem to be a way. I will chat to Vazkii about it but for now it will just have to be an annoyance.

**Comment by Insane96** [comment]
I've noticed this happens in vanilla Mineshafts too so it might be a problem on Quark's side

**Comment by Insane96** [comment]
This line is in the changelog of Quark r2.1.236
`- Fixed cave roots spawning on chunk borders and floating in mid air when the current chunk hasn't built itself properly.`
I will test to see if they still spawn mid-air

**Comment by Insane96** [comment]
Fixed as Quark r2.1.236
