### ISSUE TITLE
[question] About future updates

### ISSUE THREAD

**Issue by FuryOfFools** [svenhjol/Strange#70]
Will existing mechanics be rewritten in the future as happened with runestones? I’m just playing on a map that I don’t plan to recreate.
End and nether I can easily recreate, but I don’t want to touch the overworld

**Comment by svenhjol** [comment]
Strange is currently in beta while playtesting and features are being refined and worked on. There is a disclaimer that this might break your world since it is not final yet. Once final, worldgen features will not change. 

This is not really a bug or a feature, so I will close this ticket.

**Comment by FuryOfFools** [comment]
@svenhjol If I understand correctly, many things can change, and the release is still far.
