### ISSUE TITLE
Rune Portals Can't Be Entered in Survival

### ISSUE THREAD

**Issue by stop-x13** [svenhjol/Strange#71]
It teleports the player in creative instantly, but for survival player, the player is simply bounced back and nothing happens.

**Comment by svenhjol** [comment]
Can't seem to repeat this. I uploaded a video of it working here in survival. The mods in play are Quark, Charm, Quark Oddities and Strange.

https://mega.nz/file/qO4hjYZa#KaE3EcomnNZswMI-b3TgugQtCSFk8qpnvl-dJAa2B6M

**Comment by stop-x13** [comment]
> Can't seem to repeat this. I uploaded a video of it working here in survival. The mods in play are Quark, Charm, Quark Oddities and Strange.
> 
> https://mega.nz/file/qO4hjYZa#KaE3EcomnNZswMI-b3TgugQtCSFk8qpnvl-dJAa2B6M

Is it required to "unlock" something before this is possible? I re-tested this using Quark+Oddities, Charm, Strange and Inspirations in creative, built the portal and switched to survival, then I just couldn't enter the portal.

**Comment by svenhjol** [comment]
No it should just work. In the video I posted, I was in survival. To be fair I didn't test with Inspirations yet - there might be something in that mod that is causing the problem?

**Comment by stop-x13** [comment]
> No it should just work. In the video I posted, I was in survival. To be fair I didn't test with Inspirations yet - there might be something in that mod that is causing the problem?

I have removed inspirations and even JEI. To be precise the mod list for my test contains: AutoRegLib, Charm, Charmonium, Covalent, QuarkOddities, Quark, Strange. This is how I did my testing (to be exact):
1. create a creative world (I tried super flat & normal generation, but the result is the same)
2. get a journal and record the spawn point
3. read out the rune pattern of the portal, build the portal somewhere near
4. grab a quark's rune stone and change game mode to survival
5. active the portal by right clicking the rune stone at the portal frame, and it should light up the portal
6. try to enter the portal, but the player is bounced back, and black smoke particle comes up, indicating that the teleportation is failed (maybe?)
7. switch to creative again, and now entering the portal will instantly teleport the player to the spawn point.
BTW forge version is 31.2.8

**Comment by Coranthes** [comment]
Have you switched from creative to survival after building the portal and before activating it?  If so, I'm wondering if that could cause any issues.

**Comment by stop-x13** [comment]
> Have you switched from creative to survival after building the portal and before activating it? If so, I'm wondering if that could cause any issues.

Actually I tried both. Building the portal/activating the portal in creative or survival seemed to produce the same result.

**Comment by Coranthes** [comment]
> I have removed inspirations and even JEI. To be precised the mod list for my test contains: AutoRegLib, Charm, Charmonium, Covalent, QuarkOddities, Quark, Strange.

Is this your entire mod list?  You don't have anything else installed?

**Comment by Coranthes** [comment]
And have you made sure you have the latest version of all these mods?

**Comment by svenhjol** [comment]
It's vanilla.
