### ISSUE TITLE
Travel Journal's Photo-taking Issue

### ISSUE THREAD

**Issue by stop-x13** [svenhjol/Strange#73]
The travel journal have an issue found:
1. It seems that if you move too much by hold down one of "W/A/S/D" when trying to take a photo for a location, the "take photo" button will disappear. If no action is performed during the "take photo" action, you can re-take a picture as many times as you wish.
2. After 1, the said entry will be blocked from taking any photo.
3. Any new entry will work normally unless 1 is performed.

**Comment by svenhjol** [comment]
You can only take a photo if you're at or very close to the point where you created the entry. That's to prevent taking a photo of something that isn't the entry position. This isn't very clear in the documentation and it might be something that should be configurable. I'll have a think about it.

**Comment by svenhjol** [comment]
Todo: add documentation for being in location for photo
