### ISSUE TITLE
Mine & Slash Compatability

### ISSUE THREAD

**Issue by MokahTGS** [svenhjol/Strange#76]
I was wondering if the items from this mod (tools and weapons) are compatible or could be made compatible with Mine & Slash?

Mine & Slash adds randomly generated weapon and tool properties to all items in the game.

**Comment by svenhjol** [comment]
The tools and weapons in this mod are just very enhanced versions of normal vanilla items. The enhancements are enchantments above and beyond the normal vanilla defaults - for exampe, a `Power VI` bow.

If you experience any compatibilty issues with M&S then feel free to add to this ticket.
