### ISSUE TITLE
Discord links on Curseforge don't work

### ISSUE THREAD

**Issue by Nightcaste** [svenhjol/Strange#77]
The Discord link: https://discord.gg/BFfz58

 on this page: https://www.curseforge.com/minecraft/mc-mods/strange

When clicked, this link just reloads the curseforge page.

When manually entering the server code in Discord, Discord reports that the code (BFfz58) is either invalid or expired.

**Comment by Coranthes** [comment]
[https://discord.gg/uCAGJ2A](url)

Try this link, it should work.  
I'll leave this open until svenhjol has a chance to fix the link on curseforge.
