### ISSUE TITLE
Outer Lands as a Dimension

### ISSUE THREAD

**Issue by MokahTGS** [svenhjol/Strange#78]
I'm just wondering if you have ever thought of making the outer lands as a dimension instead of overworld generation.  This would allow modpacks that don't use normal overworld generation to use this mod.

**Comment by svenhjol** [comment]
This hasn't been considered. The distant parts of the overworld are usually unexplored by players, so it made sense to add a bit of exploration and reward to it. As for modded terrain generation, it's working pretty well with non-vanilla. If there's a normal overworld generation mod that isn't compatible, let me know and we can have a look into it.

Alternatively - you can turn off Outerlands in the config and vaults will spawn under normal locations in the overworld.

**Comment by MokahTGS** [comment]
What about a config option for adding vaults to the nether?  Perhaps as a future feature?

**Comment by svenhjol** [comment]
Vaults are generally made of overworld materials like stone, stone bricks.  There are also water sources. It wouldn't be a good fit for the nether. However, I'm open to more nether ruin ideas.

**Comment by katubug** [comment]
I just wanted to chime in and say that I would probably use the Outerlands as a dimension. My use case is as a modpack author and server administrator. I'm unsure about how far out I want my server's world to generate, but neither am I sure I want to adjust the Outerlands distance by a significant amount. Having access to them be via a portal or similar would allow for me to gate access behind endgame materials without needing to have so much generated world taking up server space.

That said, I wouldn't say I considered it a necessity or anything. I will probably just compromise on one of my preferences in the meantime. Just wanted to add my 2c!

**Comment by ridjack** [comment]
Outerlands has, sadly, been abandoned as a concept, so there won't be any additional changes to it.
