### ISSUE TITLE
Enchantments are not bound to the correct items

### ISSUE THREAD

**Issue by Insane96** [svenhjol/Strange#8]
This might be intended as I found out this config property
```toml
#If true, Strange treasure enchantments can be applied to
#books or tools on an enchanting table or anvil.
"Obtainable enchantments" = false
```

Hoes can't get Growth
![2020-03-18_20 53 27](https://user-images.githubusercontent.com/7185104/77001693-a128cc00-695a-11ea-8631-2052cc732e31.png)

Also any of the other enchantments can be applied to any tool/weapon
![2020-03-18_20 56 46](https://user-images.githubusercontent.com/7185104/77002009-1e544100-695b-11ea-80ec-ad25305a17b8.png)

Quark's Improved Tooltips doesn't show Hoes as possible enchantable item. Also the other enchantments show no available item.
![2020-03-18_20 53 31](https://user-images.githubusercontent.com/7185104/77001696-a259f900-695a-11ea-83b5-146618cd6f4e.png)
![2020-03-18_21 01 07](https://user-images.githubusercontent.com/7185104/77002317-9a4e8900-695b-11ea-8a72-61640155ecdf.png)

**Comment by svenhjol** [comment]
The idea is that these enchantments are not available to apply to items by default. It's so that you can only find them on special items found in Vault loot tables. It is intended behavior but I'm still trying to iron out some oddness. You can configure them to act as normal enchantments with the following:
	[Enchantments.TreasureEnchantments]
		#If true, Strange treasure enchantments can only be found in Vaults, not normal dungeon loot.
		"Only in vaults" = false
		#If true, Strange treasure enchantments can be applied to
		#books or tools on an enchanting table or anvil.
		"Obtainable enchantments" = true

**Comment by Insane96** [comment]
Yeah, but if I want to put one of those enchantments on a tool via /enchant I can't

**Comment by svenhjol** [comment]
You can if `Obtainable enchantments` is true.
![Screenshot from 2020-04-09 00-09-29](https://user-images.githubusercontent.com/26497903/78844825-75977f80-79f6-11ea-999b-53016529257f.png)

**Comment by svenhjol** [comment]
Is this still a thing?

**Comment by Insane96** [comment]
Ops totally forgot to test this out.
In beta 3 this still happens. Couldn't be possible to enable those enchantments via anvil (and thus enabling /enchant) and then prevent those enchantments to begin on books so you can't find them as Treasure enchantments on books but only on items?
