### ISSUE TITLE
Touching Rune Portal plays sound without teleporting

### ISSUE THREAD

**Issue by CosmicParticl** [svenhjol/Strange#81]
When trying to enter a vertical rune portal at slow speeds, the player is not teleported, but the portal sound still plays. Standing inside the portal causes the teleport sound to overlap and reach high volume levels. When entering the portal at high speeds, the issue does not occur.

**Versions (required)**
 - Strange-1.15.2-1.0.0-beta.6b2
 - Charm 1.5.9
 - Forge 31.2.0

**Comment by svenhjol** [comment]
Thanks for the report, this will be worked on for beta 6.
