### ISSUE TITLE
Can't turn in quests.

### ISSUE THREAD

**Issue by Nightcaste** [svenhjol/Strange#87]
**Describe the bug (required)**
Can't turn in quests that show completed in the UI

**Versions (required)**
 - Strange 1.14.4-1.0.0-beta.3
 - Charm 1.14.4-1.5.7
 - Forge 28.2.3

**Additional context (optional)**
I have multple quests to either craft or collect items.  Both of them have green text saying "return to the scrollkeeper to hand in your completed quest".  When I right click on the scrollkeeper, I just get his sales UI, but the quests do not complete, and I do not get the rewards.

**Comment by DarianLStephens** [comment]
I don't know if I'm just being impatient with the newly-released 1.16.4 beta, but I'm unable to turn in quests either.
There's also no quest UI in the inventory, though perhaps that's just because you need to keep track of the scrolls directly now or something.

All the items in the quest are marked with a tick, and are currently in my inventory, so I assume the quest is completed, but I can't figure out how to turn it in.

**Comment by Nightcaste** [comment]
@DarianLStephens I'm not holding my breath about any kind of fix since it's been 6 months without a peep from the developer.

**Comment by DarianLStephens** [comment]
On the contrary, the 1.16.4 beta was released just a few hours ago, and there's been a lot of github commits.

**Comment by Nightcaste** [comment]
And zero acknowledgement of this bug.

**Comment by ridjack** [comment]
@Nightcaste 1.14 is unmaintained.

@DarianLStephens  With regards to the 1.16.4 issue, what's happening when you try? Are you return to the correct Scollkeeper? Is it all quests, or just a specific one? What other mods do you have installed?

**Comment by DarianLStephens** [comment]
I've bought two scrolls off the scrollkeeper.
When I opened them, I just got the scroll's window, giving me details about the quest and reward, no quest list in my inventory.
As I completed the objectives, they were marked with a tick if I opened the scroll again.
When all the objectives had a tick next to them, I went to turn it in to the scrollkeeper, but all that happened is the trade window opening.

**Comment by Nightcaste** [comment]
Was the 1.14.4 version unmaintained back in July?

**Comment by Coranthes** [comment]
@DarianLStephens Did you try throwing the scroll at the scrollkeeper?  If I recall correctly that's how they're turned in now, and of course turned in to the same scrollkeeper you purchased them from.  Items are no longer pulled from your inventory as you collect them, so be sure you have them when you turn in the scrolls.

**Comment by DarianLStephens** [comment]
I did try to toss the scroll at them, but only gave them a few seconds to respond, which they didn't seem to.
Perhaps I need to give them longer, and maybe toss the quest items at them as well?

That whole 'same one you purchased them from' makes me wonder how the treasure scrolls are handled now. Do they just get turned in to any scrollkeeper, or is there something special about them?

**Comment by Coranthes** [comment]
@Nightcaste I don't recall exactly when, but yes, it was before July that 1.14 stopped being maintained.  I'm thinking late May or early June maybe, but I may be wrong.

**Comment by Coranthes** [comment]
I'll give the scrollkeeper a test a little later and see how it goes and get back with you on that one.  As for the treasure scrolls, yes, you can still turn them in to any scrollkeeper.

**Comment by DarianLStephens** [comment]
I've had them standing there for a bit now with the scroll at their feet, and they really don't seem to care.
![2020-12-18_11 35 33](https://user-images.githubusercontent.com/15375876/102559953-32fd7980-4125-11eb-92fb-156824eec61e.png)

**Comment by svenhjol** [comment]
I've updated the readme with a status update. More to come. https://github.com/svenhjol/Strange/blob/master/README.md

If you purchased the scroll from a scrollkeeper and completed the criteria on the scroll, the scrollkeeper you purchased it from should accept it and throw you the reward when you right-click on the villager with the scroll.

**Comment by DarianLStephens** [comment]
I'd say there's most likely a bug, then, since all the objectives are ticked, and this is the scrollkeeper I got the quest from (And the only scrollkeeper in the village).
This is all that happens when I right-click them with the scroll in hand:
![2020-12-18_11 45 22](https://user-images.githubusercontent.com/15375876/102560543-90de9100-4126-11eb-82ea-71344f24fa39.png)

**Comment by svenhjol** [comment]
Yeah, I've been able to repeat the bug just now, so I'll fix it up.

**Comment by Nightcaste** [comment]
> @Nightcaste I don't recall exactly when, but yes, it was before July that 1.14 stopped being maintained. I'm thinking late May or early June maybe, but I may be wrong.

Why did it take six months for someone to bother saying that?

**Comment by DarianLStephens** [comment]
Looking forward to the next beta version, in that case!

**Comment by svenhjol** [comment]
Reopening as the scrollkeeper fix will reference this ticket

**Comment by svenhjol** [comment]
> Looking forward to the next beta version, in that case!

here you go :) https://github.com/svenhjol/Strange/releases/download/2.1.9-hotfix1/strange-fabric-1.16.4-2.1.9-hotfix1.jar

Thanks for the patience. There are going to be a lot of rough edges.

**Comment by Nightcaste** [comment]
Why reference a ticket about an issue for a version that is no longer
supported?

**Comment by svenhjol** [comment]
It's closed now. Future tickets will reference the 1.16 version.
