### ISSUE TITLE
[MC1.15.2 - CRASH] Mobs have 0 hp and crashes the server when hit by player.

### ISSUE THREAD

**Issue by winnetrie83** [svenhjol/Strange#90]
**Describe the bug (required)**
We have this issue, we believe your mod is causing this, because the way your mod affects the mobs.
The problem exists within the Valhelsia: Origins modpack.
We found out that from x -5000 to x 5000 and  y -5000 to y 5000 is a safe spot where mobs are not effected. 
So a 10 x 10 K square. Everything outside that box is affected. Mobs who are walking in or out this zone wether recieve or loose the effect.
They all have 0 HP and black potion particles. whenever a player hits them the server immidiatly freezes and restarts.
There is no actual crashlog, so i cannot provide 1. There is absolutely no information inside. It only says the server took 60 seconds or longer for 1 tick. that's all.  

**Versions (required)**
 - Strange-1.15.2-1.0.0-beta.5.hotfix1.jar
 - Charm-1.15.2-1.5.9.jar
 - forge-31.2.31
![javaw exe Screenshot 2020 07 17 - 15 14 30 06](https://user-images.githubusercontent.com/29025144/87813043-6d56a800-c861-11ea-8dd2-fe43e03266a5.png)

We don't know yet how to fix this. 
Btw your discord invite is invalid....

The following entry in the config is perhaps conflicting:
Threshold = 150000

Our world border is at 15 000 in each direction.

**Comment by Yourname942** [comment]
What version of Forge are you using? What is your list of mods?

**Comment by winnetrie83** [comment]
> What version of Forge are you using? What is your list of mods? (I'm not part of the dev team)

I can see that. The dev(s) would actually read my post and wouldn't ask me already answered questions.

**Comment by Yourname942** [comment]
Yeah I see now (I don't know how I missed that -.-)
