### ISSUE TITLE
Discord Link not working(also where/how rare are geodes in the end?)

### ISSUE THREAD

**Issue by squirlly** [svenhjol/Strange#93]
I wanted to ask this question on the discord but your link on the curseforge page is invalid. So is the one someone posted in one of these issues. I've been flying around the end for a couple of hrs now and have seen no sign of any geodes(at least nothing that looks like what is on the wiki). Do they spawn after a certain block distance or something? Or am i just an idiot?

**Comment by Coranthes** [comment]
The geodes are just end stone on the outside. They spawn as floating spheres anywhere off the main end island.  And you  are on beta 6?

 We had to close the discord due to real life unfortunately.

**Comment by squirlly** [comment]
I have beta3. for 1.15.2. I am running biomes o plenty if for some reason that is an issue. I just havent found anything remotely spherical in the end.

**Comment by squirlly** [comment]
Wait. I am an idiot. I thought i had the latest files but yeah..... Just saw that you added them in on the beta5 patch

**Comment by Coranthes** [comment]
No worries.  That's why we ask that question.
