### ISSUE TITLE
Crash while using Stone Circles

### ISSUE THREAD

**Issue by Divineaspect** [svenhjol/Strange#94]
You must provide all the **required** information below, or your issue will be ignored/closed.

**Describe the bug (required)**
Crash when using Stone Circles to teleport. 
Might be the same as #75 

**Versions (required)**
 - Strange 1.15.2 - 1.0.0 beta 5 hotfix1
 - Charm 1.15.2 -1.5.9
- Forge  31.2.26

**Additional context (optional)**
Add any other context about the problem here that could help us track it down. For example, seed and coordinates, are you using optifine, have you changed the default config and what changes did you make?

https://pastebin.com/e1NTEmcD

**Comment by ridjack** [comment]
Unfortunately, as the 1.15 versions are no longer being maintained by anyone, this is likely to stay unresolved.
