### ISSUE TITLE
Ice Aspect Books cannot be applied to weapons

### ISSUE THREAD

**Issue by rewenx** [svenhjol/Strange#96]
I obtained a book of Ice Aspect from a villager trade. The book cannot be applied to swords or bows via the anvil, so either the book should be taken out or application via anvil should be enabled, IMO. Thanks!

**Comment by ridjack** [comment]
This needs a lot more info before it can be looked into. If this is still an issue, please feel free to open a new bug referencing this one. Keep in mind that only the current branch (1.16.4 as of writing) and the 1.12 version are being maintained.
