### ISSUE TITLE
Hotfix Crashes on Start Up

### ISSUE THREAD

**Issue by galhac** [svenhjol/Strange#97]
I've added Strange to my modpack and found that it would crash while loading the game. I tried to use a previous version to see if that would make a difference and in using the version before the hotfix, the game loaded just fine. Here's the crash log with the hotfix.
[crash-2020-10-21_12.34.14-client.txt](https://github.com/svenhjol/Strange/files/5417412/crash-2020-10-21_12.34.14-client.txt)

https://pastebin.com/vb1akfuv

**Comment by Akaitatsu** [comment]
I had something very similar happen today. I noticed that Quark is listed as a dependency for Strange. Adding Quark fixed the issue for me.
[crash-2020-11-09_16.03.52-client.txt](https://github.com/svenhjol/Strange/files/5513393/crash-2020-11-09_16.03.52-client.txt)

**Comment by ridjack** [comment]
I assume this is resolved, and in any case it's for a version that is no longer maintained.
