### ISSUE TITLE
World Generation Crash

### ISSUE THREAD

**Issue by galhac** [svenhjol/Strange#98]
[crash-2020-10-21_13.10.57-server.txt](https://github.com/svenhjol/Strange/files/5417633/crash-2020-10-21_13.10.57-server.txt)

Was walking through the world, didn't see anything so I imagine it was something it spawns underground.

https://pastebin.com/SRfKnH7u

**Comment by ridjack** [comment]
Closing as this version of Strange is no longer maintained.
