### ISSUE TITLE
(question) about the recent mod file and Discord link

### ISSUE THREAD

**Issue by elienaimg** [svenhjol/Strange#99]
The most recent version is tiny compared to all the other versions. Is the one with 1.79mb that I should use?

I would ask this on Discord but the link is down,so...
Also,can It be installed mid-game?

Strange-1.15.2-1.0.0-beta.5.hotfix1.jar	1.79 MB	

Strange-1.15.2-1.0.0-beta.3.jar                49.99 MB

**Comment by DarianLStephens** [comment]
I would also like to inquire about the discord link.
Mostly, I'm interested in trying this for 1.16 Fabric, since it's the last piece of the puzzle I need before starting to actually play in that version.

**Comment by Coranthes** [comment]
Strange is on it's way!  It's currently in the testing stage so we're finally close and very excited!  So keep an eye out for it as it should be soon.

In regard to the discord, that actually was closed the link just hasn't been taken down yet.  Sorry about the confusion there.

**Comment by DarianLStephens** [comment]
Very excited to see a 1.16.4 Fabric release, even if it's still in beta.
Looking forward to the full release!
